apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patch-backend-env.yaml

images:
  - name: sadafjamal3/digital-library-backend
    newTag: d1f3e8813b274ce6d4d7261caeeeeb1d4d62c3d9
  - name: sadafjamal3/digital-library-frontend
    newTag: d1f3e8813b274ce6d4d7261caeeeeb1d4d62c3d9
