apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - patch-backend-env.yaml

images:
  - name: sadafjamal3/digital-library-backend
    newTag: latest
  - name: sadafjamal3/digital-library-frontend
    newTag: latest
